version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

# https://www.youtube.com/watch?v=bu6IURMFZwQ&t=326s
# docker compose up -d